accounts/urls.py
from django.urls import path
from .import views
from django.contrib.auth import views as auth_views

app_name='accounts'

urlpatterns = [
    path('signup/',
        views.SignUpView.as_view(),
        name='signup'),

    path('signup_success/',
        views.SignUpSuccessView.as_view(),
        name='signup_success'),
    
    path('login/',
        auth_views.LoginView.as_view(template_name='login.html'),
        name='login'
        ),
    path('logout/',
        auth_views.LogoutView.as_view(template_name='logout.html'),
        name='logout'
        ),


]

shop/urls.py
from django.urls import path
from .import views

app_name='shop'

urlpatterns = [
    path('', views.goodsListView.as_view(), name='goods'),
    path('Listing/', views.CreateListingView.as_view(), name='Listing'),

    path('listing_done/',
        views.ListingSuccessView.as_view(),
        name='listing_done'),
]

shopproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('', include('accounts.urls')),

    #パスワードリセットのURLパターン
    path('password_reset/',
        auth_views.PasswordResetView.as_view(template_name="password_reset.html"),
        name ='password_reset'),

    #メール送信完了ページ
    path('password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"),
        name='password_reset_done'),

    #パスワードリセットページへ
    path('reset/<uidb64>/<token>',
        auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"),
        name='password_reset_confirm'),
    
    path('reset/done/',
        auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_done.html"),
        name='password_reset_complete'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):

    GROUP=(('self', '個人'),
            ('Company', '会社'))

    group = models.TextField(
        verbose_name = '所属',
        choices=GROUP)
# Create your models here.

shop/models.py
from django.db import models
from accounts.models import CustomUser

# Create your models here.

class Category(models.Model):
    title=models.CharField(
        verbose_name='カテゴリ',
        max_length=20)
    def __str__(self) -> str:
        return self.title


class good(models.Model):

    CATEGORY=(('ゲーム', 'ゲーム'),
                ('アニメ', 'アニメ'),
                ('漫画', '漫画'),
                ('同人誌', '同人誌'),
                ('CD', 'CD'),
                ('機械', '機械'),
                ('その他','その他'))

    
    QUALITY=(('未使用', '未使用'),
                ('非常に良い', '非常に良い'),
                ('良い', '良い'),
                ('普通', '普通'),
                ('悪い', '悪い'),
                ('非常に悪い', '非常に悪い'))

    user=models.ForeignKey(
        CustomUser,

        verbose_name='出品者',

        on_delete=models.CASCADE
    )

    goods_title = models.TextField(
        verbose_name = '商品名')
    category= models.CharField(
        verbose_name='カテゴリ',
        max_length=50,
        choices=CATEGORY
    )
    goods_explanation=models.TextField(null=True, blank=True,
        verbose_name='説明')
    goods_remark=models.TextField(null=True, blank=True,
        verbose_name='備考')
    goods_quality=models.TextField(
        verbose_name='品質',
        choices=QUALITY)
    goods_price=models.TextField(
        verbose_name='価格'
    )
    preview1=models.FileField(verbose_name='写真1',
                                upload_to='photos',
                                null=True,
                                blank=True
                                )
    preview2=models.FileField(verbose_name='写真2',
                                upload_to='photos',
                                blank=True,
                                null=True
                                )
    preview3=models.FileField(verbose_name='写真3',
                                upload_to='photos',
                                blank=True,
                                null=True
                                )
    preview4=models.FileField(verbose_name='写真4',
                                upload_to='photos',
                                blank=True,
                                null=True
                                )

    review=models.TextField(
        verbose_name='レビュー',
        blank=True,
        null=True
        )

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm

from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields =('username', 'email',  'password1', 'password2', 'group')

shop/forms.py
from django.forms import ModelForm
from .models import good

class ListingForm(ModelForm):
    class Meta:
        model=good
        fields=['goods_title', 'goods_explanation', 'goods_remark','goods_quality','goods_price','preview1','preview2','preview3','preview4','category',]

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView, TemplateView
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy

class SignUpView(CreateView):
    form_class=CustomUserCreationForm
    template_name="signup.html"
    success_url=reverse_lazy('accounts:signup_success')
    def form_valid(self, form):
        
        user= form.save()
        self.object = user
        return super().form_valid(form)
class SignUpSuccessView(TemplateView):
    template_name="signup_success.html"
    
    # Create your views here.

shop/views.py
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic import ListView
from .models import good
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import ListingForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required




class ListingSuccessView(TemplateView):
    template_name='Listing_success.html'


class IndexView(ListView):
    template_name='home.html'

# Create your views here.
class goodsListView(ListView):
    template_name = 'home.html' #表示したいHTML
    context_object_name = 'goods'
    model=good



@method_decorator(login_required, name='dispatch')
class CreateListingView(CreateView):
    form_class= ListingForm
    template_name="Listing.html"
    success_url=reverse_lazy('shop:listing_done')
    def form_valid(self, form):
        Listing=form.save(commit=False)
        Listing.user= self.request.user
        Listing.save()
        return super().form_valid(form)
    

accounts/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>Login</title>
    </head>
    <body>
        {% if form.error %}
            <p style="color: red">ユーザー名とパスワードが一致しません</P>
        {% endif %}
        <form method="post">
            {% csrf_token %}
            <h1>Please signin</h1>
            <label for="Username">User name</label>
            <input type="text"
                    name="username"
                    id="id_username"
                    placeholder="ユーザー名"
                    required autofocus>
            
            <label for="Password">Password</label>
            <input type="password"
                    name="password"
                    id="id_password"
                    autocomplete="current-password"
                    placeholder="パスワード"
                    required autofocus>
            <input type="submit"
                    value="ログイン">
            <br><br>
            <p><a href="{% url 'password_reset' %}">パスワードを忘れましたか？</a><p>
            <input type="hidden"
                    name="next"
                    value="{% url 'shop:goods' %}">
        </form>
    </body>
</html>

accounts/templates/logout.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>Logout</title>

    </head>
    <body>
        <h1>ログアウトが完了しました</h1>
        <p><a href="{% url 'shop:goods' %}">トップページに戻る</a><p>
    </body>
</html>

accounts/templates/password_reset.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UFT-8">

        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!--==============レイアウトを制御する独自のCSSを読み込み===============-->
        <link rel="stylesheet" type="text/css" href="https://coco-factory.jp/ugokuweb/wp-content/themes/ugokuweb/data/reset.css">
        <link rel="stylesheet" type="text/css" href="https://coco-factory.jp/ugokuweb/wp-content/themes/ugokuweb/data/6-3-1/css/6-3-1.css">

    </head>

    <body>
        <div id="video-area">
            <video id="video" poster="images/%E7%84%A1%E9%A1%8C%202023-04-26%2012-18-43.jpg" webkit-playsinline playsinline muted autoplay loop>
                <source src="{% static "movie/.mp4" %}" type="video/mp4">
            </video>
            </div>
        <h1>パスワードリセット</h1>
        <p>入力済みのメールアドレスを入力してください。
            パスワードリセットのリンクを記載したメールをすぐにお届けします。
        </p>
        <br>
        <form action="" method="POST">
            {% csrf_token %}
            {{form}}
            <!--送信ボタン-->
            <input type="submit" value="メールを受け取る" ><br>
        </form>
        <br>
        <a href="{% url 'shop:goods' %}">トップページへ</a>
        <hr>
    </body>
</html>

accounts/templates/password_reset_done.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>リセット完了</title>

    </head>
    <body>
        <h1>パスワードがリセットされました</h1>
        <p><a href="{% url 'shop:goods' %}">トップページに戻る</a><p>
    </body>
</html>

accounts/templates/password_reset_form.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>パスワード再設定</title>

    </head>
    <body>
        <h1>パスワード再設定画面</h1>
        <h2>新しいパスワードを２回入力してください。これにより正しく入力されたかを確認することができます</h2>
        <form action="" method="POST">
            {% csrf_token %}
            {{form}}
            <input type="submit" value="パスワードリセット"/>
        </form>
    </body>
</html>

accounts/templates/password_reset_sent.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>リセットメール送信</title>

    </head>
    <body>
        <h1>パスワードリセット手順をメールで送信しました。メールはすぐに届きます</h1>
        <h2>メールが届かない場合は、登録してあるメールアドレスかどうかをお確かめ下さい、迷惑メールの中もご確認ください</h2>
        <p><a href="{% url 'shop:goods' %}">トップページに戻る</a><p>
    </body>
</html>

accounts/templates/signup.html
{% load static %}
    <h1>アカウント登録</h1>
    <form method = "post">
        {% csrf_token %}
        {% for field in form %}
            <p>
                {{ field.label_tag }}<br>
                {{ field }}
                {% if field.help_text %}
                    <small style="color: grey">{{ field.help_text }}</small><!--field.help_textはこの項目は必須です等の文-->
                    
                {% endif %}
                <!--エラー発生時の設定-->
                {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                {% endfor %}


            </p>
        {% endfor %}
        <br>


        <p style="color: red">
            ※メールアドレスはパスワードリセットする際に必要にな値ますので登録をお願いします
        </p>
        <input type="submit" value="Sign up">
    </form>

        <p><a href="{% url 'shop:goods' %}">
            登録をやめてトップページに戻る</a>
        <p>

accounts/templates/signup_success.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UFT-8">

        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!--==============レイアウトを制御する独自のCSSを読み込み===============-->
        <link rel="stylesheet" type="text/css" href="https://coco-factory.jp/ugokuweb/wp-content/themes/ugokuweb/data/reset.css">
        <link rel="stylesheet" type="text/css" href="https://coco-factory.jp/ugokuweb/wp-content/themes/ugokuweb/data/6-3-1/css/6-3-1.css">

    </head>

    <body>
        <div id="video-area">
            <video id="video" poster="images/%E7%84%A1%E9%A1%8C%202023-04-26%2012-18-43.jpg" webkit-playsinline playsinline muted autoplay loop>
                <source src="{% static "#" %}" type="video/mp4">
            </video>
            </div>
        <h1>登録が完了しました</h1>
        <p><a href="{% url 'accounts:login' %}">ログインはこちらから</a><p>
    </body>
</html>

shop/templates/Listing.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UFT-8">
        <title>出品ページ</title>
    </head>
    <body>
    <br>

            <div>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <table>
                        <tr>
                            <th>カテゴリ</th>
                            <td>{{ form.category }}</td>
                        </tr>
                        <tr>
                            <th>商品名</th>
                            <td>{{ form.goods_title }}</td>
                        </tr>
                        <tr>
                            <th>説明</th>
                            <td>{{ form.goods_explanation }}</td>
                        </tr>
                            <th>備考</th>
                            <td>{{ form.goods_remark }}</td>
                        </tr>                        
                            <th>値段</th>
                            <td>{{ form.goods_price }}</td>
                        </tr>
                            <th>品質</th>
                            <td>{{ form.goods_quality }}</td>
                        </tr>
                            <th>写真１</th>
                            <td>{{ form.preview1 }}</td>
                        </tr>
                        </tr>
                            <th>写真2</th>
                            <td>{{ form.preview2 }}</td>
                        </tr>
                        </tr>
                            <th>写真3</th>
                            <td>{{ form.preview3 }}</td>
                        </tr>
                        </tr>
                            <th>写真4</th>
                            <td>{{ form.preview4 }}</td>
                        </tr>
                    </table>
                    <hr>
                    <button type="submit">出品する</button>
                </form>
            </div>
    </body>
</html>

shop/templates/Listing_success.html
<title>出品完了</title>

<h3>投稿が完了しました</h3>
{% extends 'base.html' %}

shop/templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="ja">
    <head>
        <meta charset="UFT-8">
        <title>{% block title %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        

    </head>

        <header>



        <nav id="global_navi">
        <ul>
            <li><a href="{% url 'shop:goods' %}">HOME</a></li>
            <li><a href="#">未定1</a></li>
            <li><a href="#">未定2</a></li>

        </ul>
    </nav>        
</header>
<body>


        {% if user.is_authenticated %}
        <li><a href="#">マイページ</a></li>

        <li><a href="{% url 'accounts:logout' %}"
            class="text-white">ログアウト</a></li>
        <li><a href="mailto:hmj2322015@stu.o-hara.ac.jp">連絡先</a></li>
        <a href="{% url 'shop:Listing' %}">出品する</a>
        {% else %}  
        <!--非ログイン時の表示-->
        <li><a href="{% url 'accounts:signup' %}"
            class="text-white">アカウント登録</a></li>
        <li><a href="{% url 'accounts:login' %}"
            class="text-white">ログイン</a></li>
        <li><a href="mailto:hmj2322015@stu.o-hara.ac.jp">連絡先</a></li>
        {% endif %}
        <h1>{% block h1 %}{% endblock %}</h1>
        <main>
        {% block contents %}{% endblock %}
        </main>
        

<!--フッダー-->
    <footer>
    <div id="footer_nav">
    <ul>
        <li><a href="{% url 'shop:goods' %}">HOME</a></li>
        <li><a href="#">未定1</a></li>
        <li><a href="#">未定2</a></li>
        
    </ul>
    </div>

    <small>&copy; 2023.My page.</small>
    </footer>
    <!--/フッター-->
</body>

</html>

shop/templates/home.html
{% extends 'base.html' %}
        <title>{% block title %}HOME{% endblock %}</title>
        <h1>{% block h1 %}ゾンアマ{% endblock %}</h1>

        <main>
            {% block contents %}
            {% for i in goods %}
            <p>商品名:{{i.goods_title}}<p>              
            <p>価格:{{i.goods_price}}円</p>
            {{i.preview1}}
            <p>カテゴリー:{{i.category}}</p>
            <p>出品者:{{i.user}}</p>
            <p>--------------------------------------------</p>
            {% endfor %}
            {% endblock %}
            </main>
            